# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-knx-stack.spec

# add or remove files that should be synced
synced_files:
    - python-knx-stack.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: knx-stack
# downstream (Fedora) RPM package name
downstream_package_name: knx-stack

upstream_project_url: https://github.com/majamassarini/knx-stack

jobs:
- job: copr_build
  trigger: pull_request
  owner: mmassari
  metadata:
    targets: fedora-stable
- job: copr_build
  trigger: commit
  owner: mmassari
  metadata:
    targets: fedora-stable
