# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-knx-stack.spec

# add or remove files that should be synced
files_to_sync:
    - python-knx-stack.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: knx-stack
# downstream (Fedora) RPM package name
downstream_package_name: knx-stack

release_suffix: "{PACKIT_PROJECT_BRANCH}"

jobs:
- job: copr_build
  trigger: pull_request
  targets: fedora-stable
  owner: mmassari
  project: knx-stack
- job: copr_build
  trigger: commit
  targets: fedora-stable
  owner: mmassari
  project: knx-stack
