packit_instances: ["stg"]

upstream_project_url: https://github.com/majamassarini/knx-stack
specfile_path: python-knx-stack.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets: fedora-stable
    owner: mmassari
    project: knx-stack
  - job: vm_image_build
    trigger: pull_request
    copr_chroot: fedora-39-x86_64
    owner: mmassari
    project: knx-stack
    image_customizations:
      packages: [python-knx-stack]
    image_distribution: fedora-39
    image_request:
      architecture: x86_64
      image_type: aws
      upload_request:
        type: aws
        options:
          share_with_accounts: ["727920394381"]
