# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      #- id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - --ignore=F821,BLK100
          # line break before binary operator - introduced by black (W503)
          # E203 whitespace before ':' - introduced by black (E203)
          # doctests are not well formatted, lines are too long and are not fixed by black, ignore them (W501)
          # W505 doc line too long - doctests results are too long end exceed doc line length, ignore them (W505)
          - --extend-ignore=W503,E203,E501,W505
          # black setting is 88
          - --max-line-length=88
          - --max-doc-length=120
          - --per-file-ignores=__init__.py:F401,E402
  #  - repo: https://github.com/PyCQA/isort
  #    rev: 5.10.1
  #    hooks:
  #      - id: isort
  #        args: [--profile, black]
  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v0.982
  #  hooks:
  #    - id: mypy
  #      args: [--show-error-codes, --ignore-missing-imports]
  #      additional_dependencies:
  #        [types-pkg_resources, types-requests, types-python-dateutil]
