language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - cd knx_stack
install:
  - pythom setup.py install
# command to run tests
before_script: cd knx_stack
script:
  - pytest
after_success:
  - codecov
