from knx_stack.definition.usb_hid.report_body.usb_protocol_header.bus_access_server_feature.service_identifier import ServiceId
from knx_stack.definition.usb_hid.report_body.usb_protocol_header.bus_access_server_feature.feature_identifier import FeatureId
